//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MSEditor.rc
//
#define IDC_OPEN                        1
#define IDD_MSEDITOR                    102
#define IDR_MAINFRAME                   128
#define IDD_PAGE_STATUS                 129
#define IDD_PAGE_SKILL                  130
#define IDD_PAGE_RISIST                 131
#define IDD_PAGE_ITEM                   132
#define IDD_PAGE_TROPHY                 133
#define IDD_PAGE_CRAFT                  134
#define IDD_PAGE_SCRAFT                 135
#define IDD_AIEDITOR                    136
#define IDC_FILE                        1001
#define IDC_NAME                        1002
#define IDC_LEVEL                       1003
#define IDC_EXP                         1004
#define IDC_AS                          1005
#define IDC_STATIC_FILE                 1006
#define IDC_STATIC_DATA                 1007
#define IDC_STATUS_S_HP_UP              1021
#define IDC_STATUS_S_HP_DEF             1022
#define IDC_STATUS_S_EP_UP              1024
#define IDC_STATUS_S_EP_DEF             1025
#define IDC_STATUS_S_CP_UP              1027
#define IDC_STATUS_S_CP_DEF             1028
#define IDC_RISIST_SELALL               1028
#define IDC_RISIST_SELNONE              1029
#define IDC_STATUS_S_STR                1030
#define IDC_RISIST_CUSTOM               1030
#define IDC_STATUS_S_ADF                1031
#define IDC_RISIST_CUS                  1031
#define IDC_RISIST_RESET                1032
#define IDC_STATUS_S_DEF                1034
#define IDC_STATUS_S_SPD                1035
#define IDC_STATUS_S_ATS                1038
#define IDC_STATUS_S_DEX                1039
#define IDC_STATUS_S_AGL                1042
#define IDC_STATUS_S_MOVSPD             1043
#define IDC_STATUS_S_MOV                1046
#define IDC_STATUS_S_RNG                1050
#define IDC_S_EXP                       1100
#define IDC_S_NAME                      1101
#define IDC_S_LEVEL                     1102
#define IDC_S_AS                        1103
#define IDC_SAVE                        1104
#define IDC_STATUS_HP_UP                1200
#define IDC_STATUS_HP_DEF               1201
#define IDC_STATUS_EP_UP                1202
#define IDC_STATUS_EP_DEF               1203
#define IDC_STATUS_CP_UP                1204
#define IDC_STATUS_CP_DEF               1205
#define IDC_STATUS_SPD                  1206
#define IDC_STATUS_MOVSPD               1207
#define IDC_STATUS_MOV                  1208
#define IDC_STATUS_STR                  1209
#define IDC_STATUS_DEF                  1210
#define IDC_STATUS_ATS                  1211
#define IDC_STATUS_ADF                  1212
#define IDC_STATUS_DEX                  1213
#define IDC_STATUS_AGL                  1214
#define IDC_STATUS_RNG                  1215
#define IDC_RISIST_POISON               1216
#define IDC_RISIST_FREEZE               1217
#define IDC_RISIST_PETRIFACTION         1218
#define IDC_RISIST_SLEEP                1219
#define IDC_RISIST_NOMAG                1220
#define IDC_RISIST_DARK                 1221
#define IDC_RISIST_NOCFT                1222
#define IDC_RISIST_CHAOS                1223
#define IDC_RISIST_FAINT                1224
#define IDC_RISIST_ONEHIT               1225
#define IDC_RISIST_DEFDOWN              1226
#define IDC_RISIST_ANGER                1227
#define IDC_RISIST_ARTSGUARD            1228
#define IDC_RISIST_CRAFTGUARD           1229
#define IDC_RISIST_MOVUP                1230
#define IDC_RISIST_MOVDOWN              1231
#define IDC_RISIST_STRUP                1232
#define IDC_RISIST_STRDOWN              1233
#define IDC_RISIST_DEFUP                1234
#define IDC_RISIST_DEFDOWN2             1235
#define IDC_RISIST_SPDUP                1236
#define IDC_RISIST_SPDDOWN              1237
#define IDC_RISIST_ADFUP                1238
#define IDC_RISIST_ADFDOWN              1239
#define IDC_RISIST_AGLUP                1240
#define IDC_RISIST_AGLDOWN              1241
#define IDC_RISIST_MAXGUARD             1242
#define IDC_RISIST_VANISH               1243
#define IDC_RISIST_CG                   1244
#define IDC_RISIST_FAT                  1245
#define IDC_RISIST_ATSUP                1246
#define IDC_RISIST_FORCEDEAD            1247
#define IDC_TROPHY_SEPITH_CHI           1248
#define IDC_TROPHY_SEPITH_MIZU          1249
#define IDC_TROPHY_SEPITH_HI            1250
#define IDC_TROPHY_SEPITH_KAZE          1251
#define IDC_TROPHY_SEPITH_TOKI          1252
#define IDC_TROPHY_SEPITH_SORA          1253
#define IDC_TROPHY_SEPITH_GEN           1254
#define IDC_TROPHY_SEPITH_CHI_SPIN      1255
#define IDC_TROPHY_SEPITH_MIZU_SPIN     1256
#define IDC_TROPHY_SEPITH_HI_SPIN       1257
#define IDC_TROPHY_SEPITH_KAZE_SPIN     1258
#define IDC_TROPHY_SEPITH_TOKI_SPIN     1259
#define IDC_TROPHY_SEPITH_SORA_SPIN     1260
#define IDC_TROPHY_SEPITH_GEN_SPIN      1261
#define IDC_ITEM_EQUIP1                 1262
#define IDC_ITEM_EQUIP2                 1263
#define IDC_ITEM_EQUIP3                 1264
#define IDC_ITEM_EQUIP4                 1265
#define IDC_ITEM_EQUIP5                 1266
#define IDC_ITEM_ORB1                   1267
#define IDC_ITEM_ORB2                   1268
#define IDC_ITEM_ORB3                   1269
#define IDC_ITEM_ORB4                   1270
#define IDC_STATUS_CHI                  1271
#define IDC_STATUS_MIZU                 1272
#define IDC_STATUS_HI                   1273
#define IDC_STATUS_KAZE                 1274
#define IDC_STATUS_TOKI                 1275
#define IDC_STATUS_SORA                 1276
#define IDC_STATUS_GEN                  1277
#define IDC_STATUS_CHI_SPIN             1278
#define IDC_STATUS_MIZU_SPIN            1279
#define IDC_STATUS_HI_SPIN              1280
#define IDC_STATUS_KAZE_SPIN            1281
#define IDC_STATUS_TOKI_SPIN            1282
#define IDC_STATUS_SORA_SPIN            1283
#define IDC_STATUS_GEN_SPIN             1284
#define IDC_TROPHY_DROP1                1287
#define IDC_TROPHY_DROP2                1288
#define IDC_ITEM_EQUIP_ID1              1290
#define IDC_ITEM_EQUIP_ID2              1291
#define IDC_ITEM_EQUIP_ID3              1292
#define IDC_ITEM_EQUIP_ID4              1293
#define IDC_ITEM_EQUIP_ID5              1294
#define IDC_ITEM_ORB_ID1                1295
#define IDC_ITEM_ORB_ID2                1296
#define IDC_ITEM_ORB_ID3                1297
#define IDC_ITEM_ORB_ID4                1298
#define IDC_SKILL_LIST                  1300
#define IDC_SKILL_ADD                   1301
#define IDC_SKILL_EDIT                  1302
#define IDC_SKILL_DELETE                1303
#define IDC_SKILL_MOVEUP                1304
#define IDC_SKILL_MOVEDOWN              1305
#define IDC_SKILL_ID                    1307
#define IDC_SKILL_PROPERTY              1308
#define IDC_SKILL_NAME                  1309
#define IDC_SKILL_CONDITION             1310
#define IDC_SKILL_PARAM1                1311
#define IDC_SKILL_PARAM1_ISHEX          1312
#define IDC_SKILL_TARGET                1313
#define IDC_SKILL_PARAM2                1314
#define IDC_SKILL_PARAM2_ISHEX          1315

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1313
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
