import sys
sys.path.append(r'D:\Dev\Source\Falcom\Decompiler2')

from Falcom.ED84.Parser.scena_writer_helper import *
try:
    import alchr552_hook
except ModuleNotFoundError:
    pass

scena = createScenaWriter('alchr552.dat')

# id: 0x0000 offset: 0x74
@scena.ActionTable('ActionTable')
def ActionTable():
    return ScenaActionTable(
        ScenaActionTableEntry(
            craftId       = 0x3E8,
            type          = 0x01,
            attribute     = 0x00,
            rangeType     = 0x0C,
            rng           = 0x0A,
            area          = 0x03,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 0,
            effect1       = 0x0002,
            effect2       = 0x0000,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 0,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 0,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'BE',
            action        = 'AniBtlAttack',
            name          = '普通攻擊',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3E9,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x0D,
            rng           = 0x04,
            area          = 0x08,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 20,
            effect1       = 0x0002,
            effect2       = 0x001D,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 90,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 30,
            effect2Param2 = 2,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'BEI',
            action        = 'AniBtlCraft00',
            name          = '七星連環',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EA,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x1F,
            rng           = 0x64,
            area          = 0x64,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 20,
            effect1       = 0x0016,
            effect2       = 0x0000,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 100,
            effect1Param2 = 4,
            effect1Param3 = 0,
            effect2Param1 = 0,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'BEI',
            action        = 'AniBtlCraft01',
            name          = '噩夢移換',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EB,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x0B,
            rng           = 0x00,
            area          = 0x01,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 10,
            effect1       = 0x0057,
            effect2       = 0x0000,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 0,
            effect1Param2 = 1,
            effect1Param3 = 0,
            effect2Param1 = 0,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'BMI',
            action        = 'AniBtlCraft02',
            name          = '置身替換',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EC,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x0B,
            rng           = 0x00,
            area          = 0x01,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 20,
            effect1       = 0x005D,
            effect2       = 0x0067,
            effect3       = 0x0043,
            effect4       = 0x0045,
            effect5       = 0x0000,
            effect1Param1 = 0,
            effect1Param2 = 3,
            effect1Param3 = 0,
            effect2Param1 = 10,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 999991,
            effect3Param2 = 4,
            effect3Param3 = 0,
            effect4Param1 = 999991,
            effect4Param2 = 4,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'PMBI',
            action        = 'AniBtlTensionMax',
            name          = '好戲上演',
        ),
        # ScenaActionTableEntry(
        #     craftId       = 0x3ED,
        #     type          = 0x20,
        #     attribute     = 0x00,
        #     rangeType     = 0x1F,
        #     rng           = 100,
        #     area          = 100,
        #     float08       = 0.0,
        #     float0C       = 100.0,
        #     float10       = -100.0,
        #     ariaATDelay   = 0,
        #     atDelay       = 4,
        #     effect1       = 0x00F3,
        #     effect2       = 0x0000,
        #     effect3       = 0x0000,
        #     effect4       = 0x0140,
        #     effect5       = 0x0000,
        #     effect1Param1 = 0,
        #     effect1Param2 = 4,
        #     effect1Param3 = 0,
        #     effect2Param1 = 0,
        #     effect2Param2 = 0,
        #     effect2Param3 = 0,
        #     effect3Param1 = 0,
        #     effect3Param2 = 0,
        #     effect3Param3 = 0,
        #     effect4Param1 = 50,
        #     effect4Param2 = 0,
        #     effect4Param3 = 0,
        #     effect5Param1 = 0,
        #     effect5Param2 = 0,
        #     effect5Param3 = 0,
        #     cp            = 0,
        #     flags         = 'BEI',
        #     action        = 'AniBtlAntiOrder00',
        #     name          = '僞・緋紅反轉',
        # ),
    )

# id: 0x0001 offset: 0x7D8
@scena.AlgoTable('AlgoTable')
def AlgoTable():
    return ScenaAlgoTable(
        ScenaAlgoTableEntry(
            craftId            = 0x3E9,
            aiType             = 0x02,
            probability        = 80,
            maxNumOfUses       = 0x01,
            targetType         = 0x00,
            parameters1        = [2, 1, 0],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EA,
            aiType             = 0x02,
            probability        = 40,
            maxNumOfUses       = 0xFF,
            targetType         = 0x00,
            parameters1        = [4, 1, 0],
            parameters2        = [0, 255, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EB,
            aiType             = 0x02,
            probability        = 100,
            maxNumOfUses       = 0xFF,
            targetType         = 0x00,
            parameters1        = [8, 1, 0],
            parameters2        = [0, 255, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EC,
            aiType             = 0x05,
            probability        = 100,
            maxNumOfUses       = 0x01,
            targetType         = 0x0D,
            parameters1        = [50, 0, 64],
            parameters2        = [0, 1, 0],
        ),
        # ScenaAlgoTableEntry(
        #     craftId            = 0x3ED,
        #     aiType             = 0x00,
        #     probability        = 100,
        #     maxNumOfUses       = 0x01,
        #     targetType         = 0x00,
        #     parameters1        = [0, 0, 0],
        #     parameters2        = [0, 1, 0],
        # ),
        ScenaAlgoTableEntry(
            craftId            = 0x10CF,
            aiType             = 0x00,
            probability        = 100,
            maxNumOfUses       = 0x01,
            targetType         = 0x00,
            parameters1        = [0, 0, 0],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x10D0,
            aiType             = 0x02,
            probability        = 100,
            maxNumOfUses       = 0x01,
            targetType         = 0x00,
            parameters1        = [10, 1, 0],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x0D8E,
            aiType             = 0x02,
            probability        = 100,
            maxNumOfUses       = 0x01,
            targetType         = 0x00,
            parameters1        = [10, 1, 0],
            parameters2        = [0, 1, 0],
        ),
    )

# id: 0x0002 offset: 0x93C
@scena.WeaponAttTable('WeaponAttTable')
def WeaponAttTable():
    return ScenaWeaponAttTable(3, 3, 3, 3)

# id: 0x0003 offset: 0x944
@scena.BreakTable('BreakTable')
def BreakTable():
    return ScenaBreakTable(
        # ActionID, probability
        (0x3E8, 10),
    )

def main():
    scena.run(globals())

if __name__ == '__main__':
    Try(main)
