import sys
sys.path.append(r'D:\Dev\Source\Falcom\Decompiler2')

from Falcom.ED83.Parser.scena_writer_helper import *

scena = createScenaWriter('alchr500_0.dat')

# id: 0x0000 offset: 0x4C
@scena.ActionTable('ActionTable')
def ActionTable():
    return ScenaActionTable(
        ScenaActionTableEntry(
            craftId       = 0x3E8,
            type          = 0x01,
            attribute     = 0x00,
            rangeType     = 0x0C,
            rng           = 0x04,
            area          = 0x03,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 15,
            effect1       = 0x0001,
            effect2       = 0x0000,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 15,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 0,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'EB',
            action        = 'AniBtlAttack',
            name          = '',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3E9,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x0E,
            rng           = 0x20,
            area          = 0x06,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 200,
            effect1       = 0x0001,
            effect2       = 0x001F,
            effect3       = 0x0021,
            effect4       = 0x0022,
            effect5       = 0x0000,
            effect1Param1 = 15,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 25,
            effect2Param2 = 4,
            effect2Param3 = 0,
            effect3Param1 = 25,
            effect3Param2 = 4,
            effect3Param3 = 0,
            effect4Param1 = 25,
            effect4Param2 = 4,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 5,
            flags         = 'EBI',
            action        = 'AniBtlCraft05',
            name          = '暴雨疾風槍',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EF,
            type          = 0x1F,
            attribute     = 0x00,
            rangeType     = 0x1F,
            rng           = 0x64,
            area          = 0x64,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 40,
            effect1       = 0x0001,
            effect2       = 0x0000,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 0,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 0,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 200,
            flags         = 'EBI',
            action        = 'AniBtlSCraft00',
            name          = '極·奧義·聖技·大十字·改',
        ),
    )

# id: 0x0001 offset: 0x548
@scena.AlgoTable('AlgoTable')
def AlgoTable():
    return ScenaAlgoTable(
        # ScenaAlgoTableEntry(
        #     craftId            = 0x3EC,
        #     aiType             = 0x00,
        #     probability        = 100,
        #     maxNumOfUses       = 0x01,
        #     targetType         = 0x0D,
        #     parameters1        = [10, 0, 64],
        #     parameters2        = [0, 1, 0],
        # ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EF,
            aiType             = 0x0F,
            probability        = 100,
            maxNumOfUses       = 0x01,
            targetType         = 0x01,
            parameters1        = [64, 0, 1],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3E9,
            aiType             = 0x00,
            probability        = 100,
            maxNumOfUses       = 0xFF,
            targetType         = 0x00,
            parameters1        = [0, 0, 0],
            parameters2        = [1, 255, 0],
        ),
        # ScenaAlgoTableEntry(
        #     craftId            = 0x3E8,
        #     aiType             = 0x00,
        #     probability        = 100,
        #     maxNumOfUses       = 0xFF,
        #     targetType         = 0x00,
        #     parameters1        = [0, 0, 0],
        #     parameters2        = [1, 255, 0],
        # ),
    )

def main():
    scena.run(globals())

if __name__ == '__main__':
    Try(main)
