import sys
sys.path.append(r'D:\Dev\Source\Falcom\Decompiler2')

from Falcom.ED83.Parser.scena_writer_helper import *

scena = createScenaWriter('alchr500_0.dat')

# id: 0x0000 offset: 0x4C
@scena.ActionTable('ActionTable')
def ActionTable():
    return ScenaActionTable(
        ScenaActionTableEntry(
            craftId       = 0x3E8,
            type          = 0x01,
            byte03        = 0x00,
            rangeType     = 0x0C,
            rng           = 0x04,
            area          = 0x03,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 15,
            word18        = 0x0001,
            word1A        = 0x0000,
            word1C        = 0x0000,
            word1E        = 0x0000,
            word20        = 0x0000,
            damage        = 15,
            dword28       = 0,
            dword2C       = 0,
            dword30       = 0,
            dword34       = 0,
            dword38       = 0,
            dword3C       = 0,
            dword40       = 0,
            dword44       = 0,
            dword48       = 0,
            dword4C       = 0,
            dword50       = 0,
            dword54       = 0,
            dword58       = 0,
            dword5C       = 0,
            cp            = 0,
            flags         = 'EB',
            action        = 'AniBtlAttack',
            name          = '',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3E9,
            type          = 0x1E,
            byte03        = 0x00,
            rangeType     = 0x0E,
            rng           = 32,
            area          = 6,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 200,
            word18        = 0x0001,
            word1A        = 0x001F,
            word1C        = 0x0021,
            word1E        = 0x0022,
            word20        = 0x0000,
            damage        = 15,
            dword28       = 0,
            dword2C       = 0,
            dword30       = 25,
            dword34       = 4,
            dword38       = 0,
            dword3C       = 25,
            dword40       = 4,
            dword44       = 0,
            dword48       = 25,
            dword4C       = 4,
            dword50       = 0,
            dword54       = 0,
            dword58       = 0,
            dword5C       = 0,
            cp            = 5,
            flags         = 'EBI',
            action        = 'AniBtlCraft05',
            name          = '暴雨疾風槍',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EF,
            type          = 0x1F,
            byte03        = 0x00,
            rangeType     = 0x1F,
            rng           = 0x64,
            area          = 0x64,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 40,
            word18        = 0x0001,
            word1A        = 0x0000,
            word1C        = 0x0000,
            word1E        = 0x0000,
            word20        = 0x0000,
            damage        = 0,
            dword28       = 0,
            dword2C       = 0,
            dword30       = 0,
            dword34       = 0,
            dword38       = 0,
            dword3C       = 0,
            dword40       = 0,
            dword44       = 0,
            dword48       = 0,
            dword4C       = 0,
            dword50       = 0,
            dword54       = 0,
            dword58       = 0,
            dword5C       = 0,
            cp            = 200,
            flags         = 'EBI',
            action        = 'AniBtlSCraft00',
            name          = '極·奧義·聖技·大十字·改',
        ),
    )

# id: 0x0001 offset: 0x548
@scena.AlgoTable('AlgoTable')
def AlgoTable():
    return ScenaAlgoTable(
        # ScenaAlgoTableEntry(
        #     craftId            = 0x3EC,
        #     aiType             = 0x00,
        #     probability        = 100,
        #     maxNumOfUses       = 0x01,
        #     targetType         = 0x0D,
        #     parameters1        = [10, 0, 64],
        #     parameters2        = [0, 1, 0],
        # ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EF,
            aiType             = 0x0F,
            probability        = 100,
            maxNumOfUses       = 0x01,
            targetType         = 0x01,
            parameters1        = [64, 0, 1],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3E9,
            aiType             = 0x00,
            probability        = 100,
            maxNumOfUses       = 0xFF,
            targetType         = 0x00,
            parameters1        = [0, 0, 0],
            parameters2        = [1, 255, 0],
        ),
        # ScenaAlgoTableEntry(
        #     craftId            = 0x3E8,
        #     aiType             = 0x00,
        #     probability        = 100,
        #     maxNumOfUses       = 0xFF,
        #     targetType         = 0x00,
        #     parameters1        = [0, 0, 0],
        #     parameters2        = [1, 255, 0],
        # ),
    )

def main():
    scena.run(globals())

if __name__ == '__main__':
    Try(main)
