import sys
sys.path.append(r'D:\Dev\Source\Falcom\Decompiler2')

from Falcom.ED83.Parser.scena_writer_helper import *

scena = createScenaWriter('alchr500.dat')

# id: 0x0000 offset: 0x4C
@scena.ActionTable('ActionTable')
def ActionTable():
    return ScenaActionTable(
        ScenaActionTableEntry(
            craftId       = 0x3E8,
            type          = 0x01,
            attribute     = 0x00,
            rangeType     = 0x0C,
            rng           = 0x04,
            area          = 0x03,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 15,
            effect1       = 0x0001,
            effect2       = 0x0000,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 100,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 0,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'EB',
            action        = 'AniBtlAttack',
            name          = '',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3E9,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x12,
            rng           = 0x14,
            area          = 0x06,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 20,
            effect1       = 0x0001,
            effect2       = 0x0016,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 120,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 100,
            effect2Param2 = 10,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'EBI',
            action        = 'AniBtlCraft00',
            name          = '疾風穿刺',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EA,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x1F,
            rng           = 0x64,
            area          = 0x64,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 20,
            effect1       = 0x0002,
            effect2       = 0x0019,
            effect3       = 0x000B,
            effect4       = 0x002B,
            effect5       = 0x0000,
            effect1Param1 = 110,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 100,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 50,
            effect3Param2 = 2,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'EBI',
            action        = 'AniBtlCraft01',
            name          = '大地轟雷錘',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EB,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x10,
            rng           = 0x01,
            area          = 0x0A,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 20,
            effect1       = 0x0001,
            effect2       = 0x001F,
            effect3       = 0x0021,
            effect4       = 0x0022,
            effect5       = 0x0000,
            effect1Param1 = 120,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 25,
            effect2Param2 = 4,
            effect2Param3 = 0,
            effect3Param1 = 25,
            effect3Param2 = 4,
            effect3Param3 = 0,
            effect4Param1 = 25,
            effect4Param2 = 4,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'EBI',
            action        = 'AniBtlCraft02',
            name          = '橫掃千軍',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3ED,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x12,
            rng           = 0x14,
            area          = 0x06,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 20,
            effect1       = 0x0001,
            effect2       = 0x0016,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 0,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 100,
            effect2Param2 = 10,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'EBI',
            action        = 'AniBtlCraft03',
            name          = '奧義·絕影',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EE,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x0A,
            rng           = 0x01,
            area          = 0x01,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 20,
            effect1       = 0x0001,
            effect2       = 0x0013,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 120,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 20,
            effect2Param2 = 2,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'EB',
            action        = 'AniBtlCraft04',
            name          = '影技・七柱陣',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EF,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x0E,
            rng           = 0x20,
            area          = 0x06,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 0,
            effect1       = 0x0001,
            effect2       = 0x001F,
            effect3       = 0x0021,
            effect4       = 0x0022,
            effect5       = 0x0000,
            effect1Param1 = 70,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 25,
            effect2Param2 = 4,
            effect2Param3 = 0,
            effect3Param1 = 25,
            effect3Param2 = 4,
            effect3Param3 = 0,
            effect4Param1 = 25,
            effect4Param2 = 4,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'EBI',
            action        = 'AniBtlCraft05',
            name          = '暴雨疾風槍',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EC,
            type          = 0x1E,
            attribute     = 0x00,
            rangeType     = 0x0B,
            rng           = 0x01,
            area          = 0x01,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 20,
            effect1       = 0x005D,
            effect2       = 0x0064,
            effect3       = 0x0066,
            effect4       = 0x0055,
            effect5       = 0x0000,
            effect1Param1 = 0,
            effect1Param2 = 5,
            effect1Param3 = 0,
            effect2Param1 = 10000,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 200,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 30,
            effect4Param2 = 3,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'PMBI',
            action        = 'AniBtlTensionMax',
            name          = '神聖光輝',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3FF,
            type          = 0x1F,
            attribute     = 0x00,
            rangeType     = 0x1F,
            rng           = 0x64,
            area          = 0x64,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0,
            atDelay       = 40,
            effect1       = 0x0001,
            effect2       = 0x0000,
            effect3       = 0x0000,
            effect4       = 0x0000,
            effect5       = 0x0000,
            effect1Param1 = 100,
            effect1Param2 = 0,
            effect1Param3 = 0,
            effect2Param1 = 0,
            effect2Param2 = 0,
            effect2Param3 = 0,
            effect3Param1 = 0,
            effect3Param2 = 0,
            effect3Param3 = 0,
            effect4Param1 = 0,
            effect4Param2 = 0,
            effect4Param3 = 0,
            effect5Param1 = 0,
            effect5Param2 = 0,
            effect5Param3 = 0,
            cp            = 0,
            flags         = 'EBI',
            action        = 'AniBtlSCraft00',
            name          = '極·奧義·聖技·大十字·改',
        ),
    )

# id: 0x0001 offset: 0x548
@scena.AlgoTable('AlgoTable')
def AlgoTable():
    return ScenaAlgoTable(
        ScenaAlgoTableEntry(
            craftId            = 0x3EF,
            aiType             = 0,
            probability        = 0,
            maxNumOfUses       = 0,
            targetType         = 0,
            parameters1        = [0, 0, 0],
            parameters2        = [0, 0, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3E8,
            aiType             = 0,
            probability        = 0,
            maxNumOfUses       = 0,
            targetType         = 0,
            parameters1        = [0, 0, 0],
            parameters2        = [0, 0, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3E9,
            aiType             = 0,
            probability        = 0,
            maxNumOfUses       = 0,
            targetType         = 0,
            parameters1        = [0, 0, 0],
            parameters2        = [0, 0, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EA,
            aiType             = 0,
            probability        = 0,
            maxNumOfUses       = 0,
            targetType         = 0,
            parameters1        = [0, 0, 0],
            parameters2        = [0, 0, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EB,
            aiType             = 0,
            probability        = 0,
            maxNumOfUses       = 0,
            targetType         = 0,
            parameters1        = [0, 0, 0],
            parameters2        = [0, 0, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EC,
            aiType             = 0,
            probability        = 0,
            maxNumOfUses       = 0,
            targetType         = 0,
            parameters1        = [0, 0, 0],
            parameters2        = [0, 0, 0],
        ),
        # ScenaAlgoTableEntry(
        #     craftId            = 0x3ED,
        #     aiType             = 0,
        #     probability        = 0,
        #     maxNumOfUses       = 0,
        #     targetType         = 0,
        #     parameters1        = [0, 0, 0],
        #     parameters2        = [0, 0, 0],
        # ),
        # ScenaAlgoTableEntry(
        #     craftId            = 0x3EE,
        #     aiType             = 0,
        #     probability        = 0,
        #     maxNumOfUses       = 0,
        #     targetType         = 0,
        #     parameters1        = [0, 0, 0],
        #     parameters2        = [0, 0, 0],
        # ),
        ScenaAlgoTableEntry(
            craftId            = 0x3FF,
            aiType             = 0,
            probability        = 0,
            maxNumOfUses       = 0,
            targetType         = 0,
            parameters1        = [0, 0, 0],
            parameters2        = [0, 0, 0],
        ),
    )

def main():
    scena.run(globals())

if __name__ == '__main__':
    Try(main)
