import sys
sys.path.append(r'D:\Dev\Source\Falcom\Decompiler2')

from Falcom.ED83.Parser.scena_writer_helper import *

scena = createScenaWriter('alchr501.dat')

# id: 0x0000 offset: 0x50
@scena.ActionTable('ActionTable')
def ActionTable():
    return ScenaActionTable(
        ScenaActionTableEntry(
            craftId       = 0x3E8,
            type          = 0x01,
            byte03        = 0x00,
            areaType      = 0x0C,
            rng           = 0x04,
            area          = 0x03,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0x00,
            atDelay       = 0x14,
            word18        = 0x0002,
            word1A        = 0x0000,
            word1C        = 0x0000,
            word1E        = 0x0000,
            word20        = 0x0000,
            dword24       = 0x00000064,
            dword28       = 0,
            dword2C       = 0,
            dword30       = 0,
            dword34       = 0,
            dword38       = 0,
            dword3C       = 0,
            dword40       = 0,
            dword44       = 0,
            dword48       = 0,
            dword4C       = 0,
            dword50       = 0,
            dword54       = 0,
            dword58       = 0,
            dword5C       = 0,
            cp            = 0,
            flags         = 'BE',
            action        = 'AniBtlAttack',
            name          = '普通攻擊',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3E9,
            type          = 0x1E,
            byte03        = 0x00,
            areaType      = 0x0C,
            rng           = 0x04,
            area          = 0x08,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0x0A,
            atDelay       = 0x14,
            word18        = 0x0002,
            word1A        = 0x001D,
            word1C        = 0x0000,
            word1E        = 0x0000,
            word20        = 0x0000,
            dword24       = 0x0000005A,
            dword28       = 0,
            dword2C       = 0,
            dword30       = 30,
            dword34       = 2,
            dword38       = 0,
            dword3C       = 0,
            dword40       = 0,
            dword44       = 0,
            dword48       = 0,
            dword4C       = 0,
            dword50       = 0,
            dword54       = 0,
            dword58       = 0,
            dword5C       = 0,
            cp            = 0,
            flags         = 'BEI',
            action        = 'AniBtlCraft00',
            name          = '七珠連擊',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EA,
            type          = 0x1E,
            byte03        = 0x00,
            areaType      = 0x1F,
            rng           = 0x64,
            area          = 0x64,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0x00,
            atDelay       = 0x1E,
            word18        = 0x0016,
            word1A        = 0x0000,
            word1C        = 0x0000,
            word1E        = 0x0000,
            word20        = 0x0000,
            dword24       = 0x00000064,
            dword28       = 10,
            dword2C       = 0,
            dword30       = 0,
            dword34       = 0,
            dword38       = 0,
            dword3C       = 0,
            dword40       = 0,
            dword44       = 0,
            dword48       = 0,
            dword4C       = 0,
            dword50       = 0,
            dword54       = 0,
            dword58       = 0,
            dword5C       = 0,
            cp            = 0,
            flags         = 'BEI',
            action        = 'AniBtlCraft01',
            name          = '惡夢置換',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EB,
            type          = 0x1E,
            byte03        = 0x00,
            areaType      = 0x0B,
            rng           = 0x00,
            area          = 0x01,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0x00,
            atDelay       = 0x0A,
            word18        = 0x0057,
            word1A        = 0x0000,
            word1C        = 0x0000,
            word1E        = 0x0000,
            word20        = 0x0000,
            dword24       = 0x00000000,
            dword28       = 1,
            dword2C       = 0,
            dword30       = 0,
            dword34       = 0,
            dword38       = 0,
            dword3C       = 0,
            dword40       = 0,
            dword44       = 0,
            dword48       = 0,
            dword4C       = 0,
            dword50       = 0,
            dword54       = 0,
            dword58       = 0,
            dword5C       = 0,
            cp            = 0,
            flags         = 'BMI',
            action        = 'AniBtlCraft02',
            name          = '特殊變換',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3EC,
            type          = 0x1E,
            byte03        = 0x00,
            areaType      = 0x0B,
            rng           = 0x00,
            area          = 0x01,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0x00,
            atDelay       = 0x14,
            word18        = 0x005D,
            word1A        = 0x0067,
            word1C        = 0x0043,
            word1E        = 0x0045,
            word20        = 0x0000,
            dword24       = 0x00000000,
            dword28       = 5,
            dword2C       = 0,
            dword30       = 10,
            dword34       = 0,
            dword38       = 0,
            dword3C       = 15,
            dword40       = 5,
            dword44       = 0,
            dword48       = 25,
            dword4C       = 5,
            dword50       = 0,
            dword54       = 0,
            dword58       = 0,
            dword5C       = 0,
            cp            = 0,
            flags         = 'PMBI',
            action        = 'AniBtlTensionMax',
            name          = '表演時間',
        ),
        ScenaActionTableEntry(
            craftId       = 0x3F2,
            type          = 0x14,
            byte03        = 0x02,
            areaType      = 0x0F,
            rng           = 0x64,
            area          = 0x64,
            float08       = 45.0,
            float0C       = 100.0,
            float10       = -100.0,
            ariaATDelay   = 0x00,
            atDelay       = 0x00,
            word18        = 0x0006,
            word1A        = 0x0010,
            word1C        = 0x002B,
            word1E        = 0x0000,
            word20        = 0x0000,
            dword24       = 0x00000000,
            dword28       = 0,
            dword2C       = 0,
            dword30       = 100,
            dword34       = 0,
            dword38       = 0,
            dword3C       = 0,
            dword40       = 0,
            dword44       = 0,
            dword48       = 0,
            dword4C       = 0,
            dword50       = 0,
            dword54       = 0,
            dword58       = 0,
            dword5C       = 0,
            cp            = 0,
            flags         = 'BEIQ',
            action        = 'AniBtlArtsWater03',
            name          = '鑽石新星',
        ),
    )

# id: 0x0001 offset: 0x60C
@scena.AlgoTable('AlgoTable')
def AlgoTable():
    return ScenaAlgoTable(
        ScenaAlgoTableEntry(
            craftId            = 0x3EC,
            condition          = 0x05,
            probability        = 100,
            target             = 0x01,
            targetCondition    = 0x0D,
            parameters1        = [50, 0, 64],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EA,
            condition          = 0x09,
            probability        = 100,
            target             = 0x01,
            targetCondition    = 0x0E,
            parameters1        = [64, 0, 1],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EB,
            condition          = 0x09,
            probability        = 100,
            target             = 0x01,
            targetCondition    = 0x0E,
            parameters1        = [64, 0, 1],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3E9,
            condition          = 0x09,
            probability        = 100,
            target             = 0x01,
            targetCondition    = 0x0E,
            parameters1        = [64, 0, 1],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EB,
            condition          = 0x09,
            probability        = 100,
            target             = 0x01,
            targetCondition    = 0x0E,
            parameters1        = [64, 0, 1],
            parameters2        = [0, 1, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3E9,
            condition          = 0x09,
            probability        = 100,
            target             = 0xFF,
            targetCondition    = 0x0E,
            parameters1        = [64, 0, 1],
            parameters2        = [0, 255, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EB,
            condition          = 0x02,
            probability        = 100,
            target             = 0xFF,
            targetCondition    = 0x00,
            parameters1        = [6, 1, 0],
            parameters2        = [0, 255, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3E9,
            condition          = 0x02,
            probability        = 20,
            target             = 0xFF,
            targetCondition    = 0x00,
            parameters1        = [4, 1, 0],
            parameters2        = [0, 255, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3EA,
            condition          = 0x02,
            probability        = 40,
            target             = 0xFF,
            targetCondition    = 0x00,
            parameters1        = [2, 1, 0],
            parameters2        = [0, 255, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x6F,
            condition          = 0x02,
            probability        = 60,
            target             = 0xFF,
            targetCondition    = 0x00,
            parameters1        = [2, 1, 0],
            parameters2        = [0, 255, 0],
        ),
        ScenaAlgoTableEntry(
            craftId            = 0x3E8,
            condition          = 0x00,
            probability        = 100,
            target             = 0xFF,
            targetCondition    = 0x00,
            parameters1        = [0, 0, 0],
            parameters2        = [1, 255, 0],
        ),
    )

def main():
    scena.run(globals())

if __name__ == '__main__':
    Try(main)
